### PR TITLE
Multi ticket editing

### PR DESCRIPTION
**Pull request by ja5087**
#134 

This adds buttons & associated checkboxes to the queue for Help/Resolve/Delete/Requeue selected.

Current TODO is mainly to refactor the TicketList into a Component class to let it maintain state

### CODE REVIEW

**Comment by ja5087** [comment]
It's essentially done

**Comment by pbitutsky** [comment]
screen shot 2019-02-25 at 8 47 58 pm
Why do we need a Help All and Delete All? Isn't is essentially the same thing in terms of functionality for the user?

**Comment by ja5087** [comment]
I'm guessing the original purpose was to have mass-cleanup buttons (seeing as a "help all" button for staff  is impractical at best). We might still want to be able to mass-delete tickets e.g. if office hours end abruptly.

I can definitely streamline this and perhaps offer a single select/deselect all button though.

**Comment by pbitutsky** [comment]
I think it might be dangerous to allow anyone to delete all the tickets on the queue. Maybe this should not be a feature....

**Comment by ja5087** [comment]
I've removed it.

**Pull request closed without merging**
